version: "3.8"

services:
  mongo:
    image: mongo
    networks:
      - notery-net
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    networks:
      - notery-net
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/notesdb
      - JWT_SECRET=myverysecretkey
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:

networks:
  notery-net:
